### ISSUE TITLE
Nuix Java API Project - Switching Engine Releases at runtime

### ISSUE THREAD

**Issue by chrishaupt** [Nuix/Nuix-Java-Engine-Baseline#11]
Hi Nuix-Team,

I'm currently building a Java Application that uses the Nuix JAVA API to process data. What I noticed when processing docx-files was, that the files were marked as poisoned items. I found out that this was due to the fact, that the nuix jars couldn't find the passware.dll-files. I was able to get around this issue by setting the windows system path as you describe it in the read.me for this projekt.

In the future I want to let the user decide which engine he wants to use at runtime. This isn't possible when I need to put the bin-folders from a specific engine release on the systems path. I tried a couple of other options like setting -Djava.library.path and -Djna.library.path, but the passware.dll weren't found. 

Do you have any tips for me concerning this problem?

**Comment by JuicyDragon** [comment]
Hello @chrishaupt, I believe the way Nuix Workstation (the GUI) gets around not having to have the OS `Path` environment variable include every installed version of Nuix is by setting the `Path` environment variable for the JVM process started up by `nuix_app.exe`.

For example, if you start Nuix Workstation and then run the following Ruby script in the script console:

```ruby
# Get environment variable "Path"
puts java.lang.System.getenv("Path").gsub(";","\n")
```

You should see output similar to the following:

```
C:\Program Files\Nuix\Nuix 9.2\bin
C:\Program Files\Nuix\Nuix 9.2\bin\amd64
C:\Program Files\Nuix\Nuix 9.2\bin\x86
C:\Program Files\Nuix\Nuix 9.2\jre\bin
C:\Program Files\Nuix\Nuix 9.2\jre\bin\server
C:\Python39\Scripts\
C:\Python39\
C:\WINDOWS\system32
C:\WINDOWS
etc...
```

If I then open a command prompt and echo the same variable using:

```
ECHO %path%
```

I instead get a listing without the Nuix path entries:

```
C:\Python39\Scripts\
C:\Python39\
C:\WINDOWS\system32
C:\WINDOWS
etc...
```

You see that while from the perspective of the running Nuix Java process those path values are present, the OS doesn't have them.  So I believe `nuix_app.exe` is doing the following:
1. Start JVM process which runs the Nuix main method
2. Inject into the `Path` environment variable of that JVM process the relevant additional path entries

The way I might approach this is by writing a similar executable that starts up my JVM/Nuix engine process.  I rather like C#/.NET so below here is a snippet that demonstrates the general concept in C#/.NET using the [Process](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=net-5.0) class:

```csharp
// The paths you have decided to add through whatever means, such as
// a little GUI that user selects version they want to run against
string[] additionalPaths = new string[] {
    "D:\engine-releases\9.0.1.325\bin",
    "D:\engine-releases\9.0.1.325\bin\x86",
};

Process engineProcess = new Process();

// The executable to execute
engineProcess.StartInfo.FileName = "C:\Path\To\java.exe";

// The arguments provided to executable above, things like class path, fully qualified name of class
// with static main method, maybe even Nuix specific arguments, etc
engineProcess.StartInfo.Arguments = "-classpath \"D:\\engine-releases\\9.0.1.325\\lib\\*;.\\*\" com.nuix.javaenginesimple.examples.BasicInitializationExample"

// Any additional process configuration you may want to set
engineProcess.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
engineProcess.StartInfo.CreateNoWindow = true;

// Perhaps additional configuration such as standard out and standard error redirection, etc...

// Modify the "Path" environment variable of only the JVM process we are about to start
for (string additionalPath in  additionalPaths) {
    engineProcess.EnvironmentVariables["Path"] += ";"+additionalPath;
}

// Start the process
engineProcess.Start();
```

**Comment by chrishaupt** [comment]
Thank you for this in depth answer! I thought about starting my applikation via batch script (SET Path/to/Bin). But your idea is much more convenient.

**Comment by JuicyDragon** [comment]
Hello @chrishaupt, I wanted to add that the batch file approach can work in a similar manner by using [SETLOCAL](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setlocal) and `ENDLOCAL` commands, which allows you to localize the modifications to environment variables to just between those 2 commands.  I've used both approaches (C#/.NET and batch file) to temporarily set environment variables `NUIX_USERNAME` and `NUIX_PASSWORD` to temporarily provide NMS credentials when running a script headless via `nuix_console.exe`.
