### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by tripleo1** [Nuix/Nuix-Java-Engine-Baseline#15]
What is the Nuix Java Engine for?

**Comment by JuicyDragon** [comment]
Hello @tripleo1 a good place to start if you are not familiar with our software at all might be our website:

https://www.nuix.com

Specifically relevant here is our software Nuix Workstation:

https://www.nuix.com/products/nuix-workstation

This is an example repository demonstrating the basics of getting up and running using what could be considered the API only version of Nuix Workstation.

**Comment by tripleo1** [comment]
On 4/4/22 13:26, Jason Wells wrote:
> https://www.nuix.com/products/nuix-workstation
>
> This is an example repository demonstrating the basics of getting up 
> and running using what could be considered the API only version of 
> Nuix Workstation.
>
Thank you. Will check it out.

Just to be clear, workstation is a commercial product?


Cheers

**Comment by JuicyDragon** [comment]
That is correct, Nuix is a commercial product.

**Comment by tripleo1** [comment]
Ok, final question: Does the "API" work without a license, etc?

**Comment by JuicyDragon** [comment]
The Nuix API requires a license to use it.
