### ISSUE TITLE
Not working in executable jar

### ISSUE THREAD

**Issue by VelpukondaRameshLio** [Nuix/Nuix-Java-Engine-Baseline#17]
Hi Nuix Team,

I able to run the latest released nuix engine 9.10.xx version in intellij  with VM arguments 

> --add-exports=javafx.base/com.sun.javafx.event=ALL-UNNAMED

now I generated build and run from executable jar like

> java -Xms2g -Xmx4g -jar nuixEngineTest.jar --add-exports=java.base/jdk.internal.loader=ALL-UNNAMED

not working and throw error

` ERROR com.nuix.util.jvm.classloader.EngineBootstrapClassLoader - Matching method not found for "load module "java.lang.NoSuchMethodException: org.springframework.boot.loader.LaunchedURLClassLoader.loadModule(java.lang.module.ModuleReference)        at java.lang.Class.getMethod(Class.java:2108) ~[?:?]        at com.nuix.util.jvm.classloader.EngineBootstrapClassLoader.a(SourceFile:139) ~[nuix-util-9.10.9.584.jar!/:?]        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]        at com.nuix.util.jvm.classloader.EngineBootstrapClassLoader.a(SourceFile:132) ~[nuix-util-9.10.9.584.jar!/:?]        at com.nuix.util.jvm.classloader.EngineBootstrapClassLoader.run(SourceFile:74) ~[nuix-util-9.10.9.584.jar!/:?]        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]        at com.nuix.engine.e.<init>(SourceFile:49) ~[nuix-engine-impl-9.10.9.584.jar!/:?]        at com.nuix.engine.DefaultGlobalContainerFactory.createSpi(SourceFile:23) ~[nuix-engine-impl-9.10.9.584.jar!/:?]        at nuix.engine.GlobalContainerFactory.newContainer(SourceFile:60) ~[nuix-engine-api-9.10.9.584.jar!/:?]        at com.lio.eprintutility.services.LoginServiceImpl.getAllServerLicense(LoginServiceImpl.java:255) ~[classes!/:?]        at com.lio.eprintutility.services.LoginServiceImpl$1.call(LoginServiceImpl.java:45) ~[classes!/:?]        at com.lio.eprintutility.services.LoginServiceImpl$1.call(LoginServiceImpl.java:41) ~[classes!/:?]        at javafx.concurrent.Task$TaskCallable.call(Task.java:1425) ~[javafx-graphics-11-win.jar!/:?]        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]        at javafx.concurrent.Service.lambda$executeTask$6(Service.java:725) ~[javafx-graphics-11-win.jar!/:?]        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]        at javafx.concurrent.Service.lambda$executeTask$7(Service.java:724) ~[javafx-graphics-11-win.jar!/:?]        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]        at java.lang.Thread.run(Thread.java:834) [?:?]`

Could you please help me from the above issue.

Thank you .

Regard's
Ramesh

**Comment by JuicyDragon** [comment]
Hello @VelpukondaRameshLio 

Can you share the main method of your code?  My first guess (without seeing that code) would be that the engine release directory is not being referenced or the engine `bin` and `bin/x86` directories are not on the `PATH` environment variable (assuming you are on Windows).

If you are attempting to execute one of the examples in the repository, note that they pass on the Java system property value in `nuix.engineDir` when constructing the EngineWrapper instance.

https://github.com/Nuix/Nuix-Java-Engine-Baseline/blob/master/IntelliJ/src/main/java/com/nuix/javaenginesimple/examples/BasicInitializationExample.java#L29-L34

If you do no supply that as an argument (which your example command does not) then I could imagine an issue like this occurring.

I believe you will want to add a few more startup arguments:

- `-Dnuix.engineDir="<ENGINE_RELEASE_DIRECTORY_HERE>"`
- `-Dnuix.logDir="<LOG_DIRECTORY_HERE>"`
- `-Djava.io.tmpdir="<TEMP_DIRECTORY_HERE>"`

You want to make sure that the `PATH` environment variable includes the paths to the engine `bin` and `bin/x86` directories.  The Gradle build file automatically accomplishes this for you during tests using these lines:

```java
String envPath = engineBinDirectory + ";" + engineX86BinDirectory
...
...
setEnvironment(["PATH":envPath])
```

https://github.com/Nuix/Nuix-Java-Engine-Baseline/blob/master/IntelliJ/build.gradle#L45
https://github.com/Nuix/Nuix-Java-Engine-Baseline/blob/master/IntelliJ/build.gradle#L76

But when running from a Jar independent of that, the PATH variable needs to be set for the JVM process either by having it configured in the `PATH` environment variable for the system or user, or starting the JVM using something that can configure that for just the JVM process.  An example of this is using `SETLOCAL`/`ENDLOCAL` ([docs](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/setlocal)) in a batch file which runs your command.  Another example would be starting the JVM process using [Process](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=net-7.0) class in .NET which allows you to modify environment variable for a process like this:

```csharp
Process nuixProcess = new Process();
...
...
string engineBinDir = "<ENGINE_BIN_DIR>";
string enginex86BinDir = "<ENGINE_X86_BIN_DIR>";
string existingPath = Environment.GetEnvironment("PATH");
nuixProcess.StartInfo.EnvironmentVariables.Add("PATH", existingPath+";"+engineBinDir+";"+enginex86BinDir );
```

**Comment by JuicyDragon** [comment]
So as an example of confirming what the PATH is set to, you could have this code run very early on in your project:

```java
// Print out the current PATH env var as seen by the process this code resides in
String currentPath = System.getenv("PATH");
System.out.println("Current PATH: "+currentPath);
```

Which should result in output like the following

```
Current PATH: D:\NuixEngineRelease\bin;D:\NuixEngineRelease\bin\x86
```

As you can see, my `PATH` points to both `bin` and `bin/x86` directories of my Nuix engine release.
