### ISSUE TITLE
How do i implement Processor for addeing evidence to case

### ISSUE THREAD

**Issue by VelpukondaRameshLio** [Nuix/Nuix-Java-Engine-Baseline#5]
Hi,
I have implemented nuix java based api with this i'm able to connect to licensed server then i got Utility instance so that i can able to create new case or open existed case. now i want to add evidence to existing case and need to process.

please could you help. thanks in advance

**Comment by JuicyDragon** [comment]
Hello @VelpukondaRameshLio I've changed the structure of the repo a little bit to be a little more example oriented and included a basic example of loading data into a case which can be found here:

https://github.com/Nuix/Nuix-Java-Engine-Baseline/blob/master/Java/src/main/java/com/nuix/javaenginesimple/examples/LoadDataIntoCaseExample.java

**Comment by JuicyDragon** [comment]
Hello @VelpukondaRameshLio I am going to close this issue, as I believe I have addressed your question, but feel free to open a new issue if you have further questions.
