### ISSUE TITLE
CLS licence never gets released

### ISSUE THREAD

**Issue by robinpower** [Nuix/Nuix-Java-Engine-Baseline#7]
https://github.com/Nuix/Nuix-Java-Engine-Baseline/blob/28d8d2f9fa02fda90a8aa8fd6911211d5a0b8018/Java/src/main/java/com/nuix/javaenginesimple/EngineWrapper.java#L306

In the cloud licence mode of acquiring a licence the time to live on the acquired licence is typically going to be a long time so you should release it when the consumer's accept call is done.

That is, unless you want to support some sort of semi-offline mode like nuix console does with its -release switch (by default it holds the licence for another session on the same machine). In which case this wrapper would provide a means to specify whether to release the licence on cleanup or not.

**Comment by JuicyDragon** [comment]
Thank you @robinpower for looking over this.  I appreciate the feedback.  I was under the impression that closing the engine instance in the finally block would release the license back:
https://github.com/Nuix/Nuix-Java-Engine-Baseline/blob/28d8d2f9fa02fda90a8aa8fd6911211d5a0b8018/Java/src/main/java/com/nuix/javaenginesimple/EngineWrapper.java#L317-L322

Based on the Engine.close documentation:
![image](https://user-images.githubusercontent.com/11775738/88406728-f0a65b00-cd85-11ea-9fcd-03f99e2a6fb4.png)

Am I misunderstanding something?  Is there a more appropriate approach I should be using? Thanks

**Comment by thlv** [comment]
@JuicyDragon 

There is a possibility that the script may terminate abnormally in which case *engine.close* may not be called. I have added a *shutdown hook* which runs in a different thread to attempt to call *engine.close* again when the main thread is terminated. If *engine.close* is called in the main thread successfully, this second call in the shutdown hook will not have any effect.

I have tried three ways to test the shutdown hook to release the licences successfully. All three happen before *engine.close* in the main thread is called
-  calling System.exit
-  throwing RuntimeExcepton
-  stopping the process (eg. kill 12345)

The Main program creates an instance of EngineWrapper. It adds a shutdown hook to the Main program's runtime. The shutdown hook will call the EngineWrapper's close method to perform clean up when the Main program terminates.

```
    public static void main(String[] args) throws Exception
    {
        String path = "/engine-dist-x.y.z-changeme";
        File file = new File(path);
        EngineWrapper wrapper = new EngineWrapper(path);

        // Shutdown hook
        Runtime.getRuntime().addShutdownHook(new Thread(wrapper::close));
        
        try {
            wrapper.withCloudLicense("username-changeme", "password-changme", utilities -> {
                logger.info("do something with utilities");
                // test the shutdown hook with exit calls and throwing run time exceptions here
                // exit(-1);
                // throw new RuntimeException();
            });
        } finally {
            // if RuntimeException occurs, need to call exit to terminate 
            // otherwise the program lingers and the shutdown hook will not be invoked.
            exit(0);
        }
    }
```
The close method is added to the EngineWrapper to call *engine.close*
```
    public void close()
    {
        logger.info("Shutdown hook starts);
        if (engine != null)
        {
            logger.info("Shutdown hook closing engine");
            engine.close();
        }         
	logger.info("Shutdown hook ends);
    }	
```

**Comment by JuicyDragon** [comment]
@thlv that is a nice solution to the problem, thank you for providing that.  I have made some changes to the EngineWrapper class to support this similar workflow: 4cd8b641e2e9421058c048d7df13ed474e98d1b4

So what I have done is modified EngineWrapper to implement [AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) and in the close method call Engine.close as you suggested.  Then before handing the Utilities over to provided `Consumer<Utilities>` a similar shutdown hook is registered.  Upon calling the close method of EngineWrapper, the shutdown hook is unregistered.
